workspace(name = "p1")

load("//repositories:stage1.bzl", p1_stage1 = "stage1")

p1_stage1()

load("//repositories:stage2.bzl", p1_stage2 = "stage2")

p1_stage2()

load("//repositories:stage3.bzl", p1_stage3 = "stage3")

p1_stage3()
