workspace(name = "p1")

########################################
# bazel_tools
########################################
#
# These rules are included as part of Bazel.
# Reference: https://github.com/bazelbuild/bazel

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

########################################
# p1_repositories
########################################
#
# This rule configures the following repositories:
# * bazel_toolchains: https://github.com/bazelbuild/bazel-toolchains
# * boost

load("//repositories:repositories.bzl", p1_repositories = "repositories")

p1_repositories()

########################################

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

http_archive(
    name = "gtest",
    build_file = "@com_google_or_tools//bazel:gtest.BUILD",
    strip_prefix = "googletest-release-1.8.0/googletest",
    url = "https://github.com/google/googletest/archive/release-1.8.0.zip",
)

http_archive(
    name = "glpk",
    build_file = "@com_google_or_tools//bazel:glpk.BUILD",
    sha256 = "9a5dab356268b4f177c33e00ddf8164496dc2434e83bd1114147024df983a3bb",
    url = "http://ftp.gnu.org/gnu/glpk/glpk-4.52.tar.gz",
)

########################################
# bazel_toolchains_repositories
########################################
#
# This rule configures the following repositories:
# * io_bazel_rules_docker: https://github.com/bazelbuild/rules_docker
# * bazel_skylib: https://github.com/bazelbuild/bazel-skylib
# * bazel_gpg: https://bazel.build/bazel-release.pub.gpg

load(
    "@bazel_toolchains//repositories:repositories.bzl",
    bazel_toolchains_repositories = "repositories",
)

bazel_toolchains_repositories()

########################################
# docker_toolchain_configure
########################################
#
# This call is optional but should go before container_repositories
# which will otherwise provide a default.

load(
    "@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    docker_toolchain_configure = "toolchain_configure",
)

docker_toolchain_configure(
    name = "docker_config",
)
